### ISSUE TITLE
Link is not rendered in the README.md

### ISSUE THREAD

**Issue by apaleyes** [amzn/xfer#9]
Github apparently has a bug in its markdown rendering when it won't properly show links that are not http or https. Example of where this is discussed: https://github.com/gollum/gollum/issues/759

The first link in the README.md is ftp so is affected. As a solution, the link could be to the web page that references the actual paper: http://pages.cs.wisc.edu/~shavlik/abstracts/torrey.handbook09.abstract.html

**Comment by palindromik** [comment]
Thanks for checking this. I'll update the ftp link to http

**Comment by palindromik** [comment]
Updated and the http link now renders in README
